### ISSUE TITLE
关于目录结构

### ISSUE THREAD

**Issue by spland** [1024-lab/smart-admin#11]
controller跟service为什么放一个目录，好奇怪，不应该是controller单独一个目录，然后service一个目录，dao作为一个目录，这样才是清晰的做法啊

**Comment by spland** [comment]
像EmailController跟EmailService居然放一个目录，为啥呢？

**Comment by ykvie** [comment]
有意思

**Comment by 1024-lab** [comment]
可以看下文档的说明：https://smartadmin.vip/views/v2/guide/JavaProject.html#_4-4%E3%80%81%E9%87%8D%E7%82%B9module%E5%8C%85
