### ISSUE TITLE
提一下小建议

### ISSUE THREAD

**Issue by Huali23** [1024-lab/smart-admin#16]
确实很规范，一直想找这样的项目。  
但是有一点小瑕疵，提一下建议哈：  
1.如果用习惯了restful，感觉还是restful风格接口可读性比较好。  
2.controller service dao 感觉还是分开放比较清晰。  
3.idea打开还有很多标黄的地方，比如说泛型，无效的判空等代码，感觉可以再优化一下。

**Comment by 1024-lab** [comment]
每个项目有每个项目的风格哈
